[tox]
env_list = django42, django52, django60

[testenv]
deps =
    dj-database-url>=3.1.2
    psycopg>=3.3.3
    pytest>=8.0
    pytest-django>=4.9
    django42: django>=4.2,<4.3
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
commands = pytest {posargs}
